// Generated by gencpp from file waterplus_map_tools/ServoWrite.msg
// DO NOT EDIT!


#ifndef WATERPLUS_MAP_TOOLS_MESSAGE_SERVOWRITE_H
#define WATERPLUS_MAP_TOOLS_MESSAGE_SERVOWRITE_H

#include <ros/service_traits.h>


#include <waterplus_map_tools/ServoWriteRequest.h>
#include <waterplus_map_tools/ServoWriteResponse.h>


namespace waterplus_map_tools
{

struct ServoWrite
{

typedef ServoWriteRequest Request;
typedef ServoWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoWrite
} // namespace waterplus_map_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waterplus_map_tools::ServoWrite > {
  static const char* value()
  {
    return "f90a4a27fdac2d3886d60d19d2b742b2";
  }

  static const char* value(const ::waterplus_map_tools::ServoWrite&) { return value(); }
};

template<>
struct DataType< ::waterplus_map_tools::ServoWrite > {
  static const char* value()
  {
    return "waterplus_map_tools/ServoWrite";
  }

  static const char* value(const ::waterplus_map_tools::ServoWrite&) { return value(); }
};


// service_traits::MD5Sum< ::waterplus_map_tools::ServoWriteRequest> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::ServoWrite > 
template<>
struct MD5Sum< ::waterplus_map_tools::ServoWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::ServoWrite >::value();
  }
  static const char* value(const ::waterplus_map_tools::ServoWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::ServoWriteRequest> should match 
// service_traits::DataType< ::waterplus_map_tools::ServoWrite > 
template<>
struct DataType< ::waterplus_map_tools::ServoWriteRequest>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::ServoWrite >::value();
  }
  static const char* value(const ::waterplus_map_tools::ServoWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waterplus_map_tools::ServoWriteResponse> should match 
// service_traits::MD5Sum< ::waterplus_map_tools::ServoWrite > 
template<>
struct MD5Sum< ::waterplus_map_tools::ServoWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waterplus_map_tools::ServoWrite >::value();
  }
  static const char* value(const ::waterplus_map_tools::ServoWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waterplus_map_tools::ServoWriteResponse> should match 
// service_traits::DataType< ::waterplus_map_tools::ServoWrite > 
template<>
struct DataType< ::waterplus_map_tools::ServoWriteResponse>
{
  static const char* value()
  {
    return DataType< ::waterplus_map_tools::ServoWrite >::value();
  }
  static const char* value(const ::waterplus_map_tools::ServoWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WATERPLUS_MAP_TOOLS_MESSAGE_SERVOWRITE_H
