set(_CATKIN_CURRENT_PACKAGE "LaserUndistortion")
set(LaserUndistortion_VERSION "0.0.0")
set(LaserUndistortion_MAINTAINER "eventec <eventec@todo.todo>")
set(LaserUndistortion_PACKAGE_FORMAT "1")
set(LaserUndistortion_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(LaserUndistortion_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(LaserUndistortion_BUILDTOOL_DEPENDS "catkin")
set(LaserUndistortion_BUILDTOOL_EXPORT_DEPENDS )
set(LaserUndistortion_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(LaserUndistortion_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(LaserUndistortion_TEST_DEPENDS )
set(LaserUndistortion_DOC_DEPENDS )
set(LaserUndistortion_URL_WEBSITE "")
set(LaserUndistortion_URL_BUGTRACKER "")
set(LaserUndistortion_URL_REPOSITORY "")
set(LaserUndistortion_DEPRECATED "")