# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM0
baud: 57600
timeout: 0.4

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 10
base_controller_timeout: 0.5

#publish_tf: True
# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.1
wheel_track: 0.163    # L value
encoder_resolution: 13 #DFRobot 12V DC 146rpm encoder motors
gear_reduction: 51
motors_reversed: True
debugPID: False
linear_scale_correction: 1.0  #0.3m/s
angular_scale_correction: 0.98      #1

# === PID parameters
accel_limit: 1

AWheel_Kp: 11
AWheel_Kd: 15
AWheel_Ki: 0
AWheel_Ko: 50

BWheel_Kp: 11
BWheel_Kd: 25
BWheel_Ki: 0
BWheel_Ko: 50

CWheel_Kp: 11
CWheel_Kd: 16
CWheel_Ki: 0
CWheel_Ko: 50

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  #antiDropIR_front: {pin: 22, type: Digital, rate: 5, direction: input},
  #antiHitIR_front:  {pin: 1, type: GP2Y0A41, rate: 2, direction: input},
  #antiHitIR_right:  {pin: 2, type: GP2Y0A41, rate: 2, direction: input},
  #antiHitIR_left:   {pin: 3, type: GP2Y0A41, rate: 2, direction: input},
  #motors_current:   {pin: 0, type: MotorTotalCurrent, rate: 2},
  #voltage_sensor:   {pin: 4, type: Voltage, rate: 0.2, direction: input}
}

