obstacle_range: 2.0
raytrace_range: 3.0
robot_radius: 0.16
inflation_radius: 0.1
max_obstacle_height: 0.4
min_obstacle_height: 0.05
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.3}

